{% set version = "0.1.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pkgfilecache
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pkgfilecache_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pkgfilecache/pkgfilecache_{{ version }}.tar.gz
  sha256: 6b453f71a8b29118d2898428b08d92966c2e34d47ffb91af339a1012ca9ff15b

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-curl
    - r-downloader
    - r-rappdirs
  run:
    - r-base
    - r-curl
    - r-downloader
    - r-rappdirs

test:
  requires:
    - r-testthat >=2.1.0
  source_files:
    - tests/
  commands:
    - $R -e "library('pkgfilecache')"                                        # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"  # [not win]
    - "\"%R%\" -e \"library('pkgfilecache')\""                                        # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://github.com/dfsp-spirit/pkgfilecache
  license: MIT
  summary: |
    Manage optional data for your package. The data can be hosted anywhere, and you have
    to give a Uniform Resource Locator (URL) for each file. File integrity checks are
    supported. This is useful for package authors who need to ship more than the 5 Megabyte
    of data currently allowed by the the Comprehensive R Archive Network (CRAN).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - dipterix
    - dfsp-spirit
    - conda-forge/r

# Package: pkgfilecache
# Type: Package
# Title: Download and Manage Optional Package Data
# Version: 0.1.4
# Authors@R: person("Tim", "Schafer", role = c("aut", "cre"), email = "ts+code@rcmd.org", comment = c(ORCID = "0000-0002-3683-8070"))
# Maintainer: Tim Schafer <ts+code@rcmd.org>
# Description: Manage optional data for your package. The data can be hosted anywhere, and you have to give a Uniform Resource Locator (URL) for each file. File integrity checks are supported. This is useful for package authors who need to ship more than the 5 Megabyte of data currently allowed by the the Comprehensive R Archive Network (CRAN).
# License: MIT + file LICENSE
# Encoding: UTF-8
# URL: https://github.com/dfsp-spirit/pkgfilecache
# BugReports: https://github.com/dfsp-spirit/pkgfilecache/issues
# Suggests: knitr, rmarkdown, testthat (>= 2.1.0)
# Imports: downloader, rappdirs
# VignetteBuilder: knitr
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2021-05-17 12:44:42 UTC; timschaefer
# Author: Tim Schafer [aut, cre] (<https://orcid.org/0000-0002-3683-8070>)
# Repository: CRAN
# Date/Publication: 2021-05-17 17:20:05 UTC
